# ==============================================================================
# Figure 4F: In silico transcription factor perturbation analysis
#
# Description:
# Performs CellOracle knockout simulations for selected transcription factors
# and generates simulated cell-state transition vector plots and related QC
# visualizations.
#
# TFs analyzed:
#   ZBTB7C, FOXA2, EBF1, ESR1, STAT1, PLAGL1, LMX1A, FOXO1
#
# Inputs:
#   CellOracle `oracle` object generated by the upstream CellOracle workflow.
#
# Outputs:
#   figures/Figure4/CellOracle/
#
# Environment:
#   Python package versions are recorded in environment.yml.
# ==============================================================================


# ==============================================================================
# Packages and settings
# ==============================================================================

from pathlib import Path

import matplotlib.pyplot as plt
import scanpy as sc


# ==============================================================================
# Output directory
# ==============================================================================

output_dir = Path("figures/Figure4/CellOracle")
output_dir.mkdir(parents=True, exist_ok=True)


# ==============================================================================
# Figure 4F: CellOracle knockout simulations
# ==============================================================================

tfs_to_simulate = [
    "ZBTB7C",
    "FOXA2",
    "EBF1",
    "ESR1",
    "STAT1",
    "PLAGL1",
    "LMX1A",
    "FOXO1",
]

for goi in tfs_to_simulate:

    print(f"Running CellOracle simulation for {goi}")

    # --------------------------------------------------------------------------
    # Simulate TF knockout
    # --------------------------------------------------------------------------

    oracle.simulate_shift(
        perturb_condition={goi: 0.0},
        n_propagation=3,
    )

    oracle.estimate_transition_prob(
        n_neighbors=200,
        knn_random=True,
        sampled_fraction=1,
    )

    oracle.calculate_embedding_shift(
        sigma_corr=0.05
    )


    # --------------------------------------------------------------------------
    # Simulated versus randomized shift vectors
    # --------------------------------------------------------------------------

    fig, ax = plt.subplots(1, 2, figsize=(13, 6))

    scale = 50

    oracle.plot_quiver(
        scale=scale,
        ax=ax[0],
    )

    ax[0].set_title(
        f"Simulated cell identity shift vector: {goi} KO"
    )

    oracle.plot_quiver_random(
        scale=scale,
        ax=ax[1],
    )

    ax[1].set_title(
        "Randomized simulation vector"
    )

    plt.savefig(
        output_dir / f"{goi}_shift_vectors_scale50.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


    # --------------------------------------------------------------------------
    # Imputed TF expression
    # --------------------------------------------------------------------------

    sc.pl.umap(
        oracle.adata,
        color=[goi],
        layer="imputed_count",
        show=False,
    )

    plt.savefig(
        output_dir / f"{goi}_imputed_count_UMAP.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


    # --------------------------------------------------------------------------
    # Determine appropriate mass threshold
    # --------------------------------------------------------------------------

    n_grid = 40

    oracle.calculate_p_mass(
        smooth=0.8,
        n_grid=n_grid,
        n_neighbors=200,
    )

    oracle.suggest_mass_thresholds(
        n_suggestion=12
    )

    plt.savefig(
        output_dir / f"{goi}_mass_threshold_suggestions.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


    # --------------------------------------------------------------------------
    # Apply mass filter
    # --------------------------------------------------------------------------

    min_mass = 10

    oracle.calculate_mass_filter(
        min_mass=min_mass,
        plot=True,
    )

    plt.savefig(
        output_dir / f"{goi}_mass_filter_{min_mass}.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()


    # --------------------------------------------------------------------------
    # Simulation flow on grid
    # --------------------------------------------------------------------------

    fig, ax = plt.subplots(1, 2, figsize=(13, 6))

    scale_simulation = 30

    oracle.plot_simulation_flow_on_grid(
        scale=scale_simulation,
        ax=ax[0],
    )

    ax[0].set_title(
        f"Simulated cell identity shift vector: {goi} KO"
    )

    oracle.plot_simulation_flow_random_on_grid(
        scale=scale_simulation,
        ax=ax[1],
    )

    ax[1].set_title(
        "Randomized simulation vector"
    )

    plt.savefig(
        output_dir / f"{goi}_simulation_flow_grid.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)